baseURL = "https://example.com"
title = "Pelican Casino"
defaultContentLanguage = "pt"

[taxonomies]
  tag = ""
  category = ""

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  defaultLang = "pt"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]


  
  #[languages.cs]
   
  # weight = 1
  
  #  languageName = "Czech"
  
  #  languageCode = "cs-cz"
  
  #  title = "Pelican Casino"
  
  #  contentDir = "content/cs"
  
  #[languages.en]
  
  #  weight = 2
   
  # languageName = "English"
  
  #  languageCode = "en-gb"
   
  # title = "Pelican Casino"
    
  #contentDir = "content/en"

  [languages.pt]
    weight = 3
    languageName = "Portuguese"
    languageCode = "pt-pt"
    title = "Pelican Casino"
    contentDir = "content/pt"
   #  [languages.si]
    #   weight = 4
     #  languageName = "Slovenian"
     #  languageCode = "sl-si"
     #  title = "Pelican Casino"
     #  contentDir = "content/si"
   #  [languages.dk]
    #   weight = 5
   #    languageName = "Danish"
   #    languageCode = "da-dk"
    #   title = "Pelican Casino"
    #   contentDir = "content/dk"

  # [languages.cz]
  #   weight = 1
  #   languageName = "Czech"
  #   languageCode = "cs-cz"
  #   title = "Pelican Casino"
  #   contentDir = "content/cz"

  # [languages.sk]
  #   weight = 1
  #   languageName = "Slovak"
  #   languageCode = "sk-sk"
  #   title = "Pelican Casino"
  #   contentDir = "content/sk"

  # [languages.pl]
  #   weight = 1
  #   languageName = "Polish"
  #   languageCode = "pl-pl"
  #   title = "Pelican Casino"
  #   contentDir = "content/pl"

  # [languages.de]
  #   weight = 1
  #   languageName = "German"
  #   languageCode = "de-de"
  #   title = "Pelican Casino"
  #   contentDir = "content/de"

  # [languages.at]
  #   weight = 1
  #   languageName = "German (Austria)"
  #   languageCode = "de-at"
  #   title = "Pelican Casino"
  #   contentDir = "content/at"

  # [languages.ch]
  #   weight = 1
  #   languageName = "German (Switzerland)"
  #   languageCode = "de-ch"
  #   title = "Pelican Casino"
  #   contentDir = "content/ch"

  # [languages.fr]
  #   weight = 1
  #   languageName = "French"
  #   languageCode = "fr-fr"
  #   title = "Pelican Casino"
  #   contentDir = "content/fr"

  # [languages.es]
  #   weight = 1
  #   languageName = "Spanish"
  #   languageCode = "es-es"
  #   title = "Pelican Casino"
  #   contentDir = "content/es"

  # [languages.pt]
  #   weight = 1
  #   languageName = "Portuguese"
  #   languageCode = "pt-pt"
  #   title = "Pelican Casino"
  #   contentDir = "content/pt"

  # [languages.it]
  #   weight = 1
  #   languageName = "Italian"
  #   languageCode = "it-it"
  #   title = "Pelican Casino"
  #   contentDir = "content/it"

  # [languages.gr]
  #   weight = 1
  #   languageName = "Greek"
  #   languageCode = "el-gr"
  #   title = "Pelican Casino"
  #   contentDir = "content/gr"

  # [languages.ro]
  #   weight = 1
  #   languageName = "Romanian"
  #   languageCode = "ro-ro"
  #   title = "Pelican Casino"
  #   contentDir = "content/ro"

  # [languages.bg]
  #   weight = 1
  #   languageName = "Bulgarian"
  #   languageCode = "bg-bg"
  #   title = "Pelican Casino"
  #   contentDir = "content/bg"

  # [languages.hu]
  #   weight = 1
  #   languageName = "Hungarian"
  #   languageCode = "hu-hu"
  #   title = "Pelican Casino"
  #   contentDir = "content/hu"

  # [languages.hr]
  #   weight = 1
  #   languageName = "Croatian"
  #   languageCode = "hr-hr"
  #   title = "Pelican Casino"
  #   contentDir = "content/hr"

  # [languages.rs]
  #   weight = 1
  #   languageName = "Serbian"
  #   languageCode = "sr-rs"
  #   title = "Pelican Casino"
  #   contentDir = "content/rs"

  # [languages.si]
  #   weight = 1
  #   languageName = "Slovenian"
  #   languageCode = "sl-si"
  #   title = "Pelican Casino"
  #   contentDir = "content/si"

  # [languages.ba]
  #   weight = 1
  #   languageName = "Bosnian"
  #   languageCode = "bs-ba"
  #   title = "Pelican Casino"
  #   contentDir = "content/ba"

  # [languages.mk]
  #   weight = 1
  #   languageName = "Macedonian"
  #   languageCode = "mk-mk"
  #   title = "Pelican Casino"
  #   contentDir = "content/mk"

  # [languages.al]
  #   weight = 1
  #   languageName = "Albanian"
  #   languageCode = "sq-al"
  #   title = "Pelican Casino"
  #   contentDir = "content/al"

  # [languages.lv]
  #   weight = 1
  #   languageName = "Latvian"
  #   languageCode = "lv-lv"
  #   title = "Pelican Casino"
  #   contentDir = "content/lv"

  # [languages.lt]
  #   weight = 1
  #   languageName = "Lithuanian"
  #   languageCode = "lt-lt"
  #   title = "Pelican Casino"
  #   contentDir = "content/lt"

  # [languages.ee]
  #   weight = 1
  #   languageName = "Estonian"
  #   languageCode = "et-ee"
  #   title = "Pelican Casino"
  #   contentDir = "content/ee"

  # [languages.fi]
  #   weight = 1
  #   languageName = "Finnish"
  #   languageCode = "fi-fi"
  #   title = "Pelican Casino"
  #   contentDir = "content/fi"

  # [languages.se]
  #   weight = 1
  #   languageName = "Swedish"
  #   languageCode = "sv-se"
  #   title = "Pelican Casino"
  #   contentDir = "content/se"

  # [languages.no]
  #   weight = 1
  #   languageName = "Norwegian"
  #   languageCode = "nb-no"
  #   title = "Pelican Casino"
  #   contentDir = "content/no"


  # [languages.uk]
  #   weight = 1
  #   languageName = "Ukrainian"
  #   languageCode = "uk-ua"
  #   title = "Pelican Casino"
  #   contentDir = "content/uk"

  # [languages.by]
  #   weight = 1
  #   languageName = "Belarusian"
  #   languageCode = "be-by"
  #   title = "Pelican Casino"
  #   contentDir = "content/by"

  # [languages.ie]
  #   weight = 1
  #   languageName = "Irish"
  #   languageCode = "ga-ie"
  #   title = "Pelican Casino"
  #   contentDir = "content/ie"

  # [languages.is]
  #   weight = 1
  #   languageName = "Icelandic"
  #   languageCode = "is-is"
  #   title = "Pelican Casino"
  #   contentDir = "content/is"

  # ———— Нефтяной Ближний Восток ————
  # [languages.sa]
  #   weight = 1
  #   languageName = "Arabic (Saudi Arabia)"
  #   languageCode = "ar-sa"
  #   title = "Pelican Casino"
  #   contentDir = "content/sa"

  # [languages.ae]
  #   weight = 1
  #   languageName = "Arabic (UAE)"
  #   languageCode = "ar-ae"
  #   title = "Pelican Casino"
  #   contentDir = "content/ae"

  # [languages.kw]
  #   weight = 1
  #   languageName = "Arabic (Kuwait)"
  #   languageCode = "ar-kw"
  #   title = "Pelican Casino"
  #   contentDir = "content/kw"

  # [languages.qa]
  #   weight = 1
  #   languageName = "Arabic (Qatar)"
  #   languageCode = "ar-qa"
  #   title = "Pelican Casino"
  #   contentDir = "content/qa"

  # [languages.om]
  #   weight = 1
  #   languageName = "Arabic (Oman)"
  #   languageCode = "ar-om"
  #   title = "Pelican Casino"
  #   contentDir = "content/om"

  # [languages.bh]
  #   weight = 1
  #   languageName = "Arabic (Bahrain)"
  #   languageCode = "ar-bh"
  #   title = "Pelican Casino"
  #   contentDir = "content/bh"

  # [languages.iq]
  #   weight = 1
  #   languageName = "Arabic (Iraq)"
  #   languageCode = "ar-iq"
  #   title = "Pelican Casino"
  #   contentDir = "content/iq"

  # [languages.ir]
  #   weight = 1
  #   languageName = "Persian"
  #   languageCode = "fa-ir"
  #   title = "Pelican Casino"
  #   contentDir = "content/ir"
